// Code generated by MockGen. DO NOT EDIT.
// Source: pwned_validator.go
//
// Generated by this command:
//
//	mockgen -source=pwned_validator.go -destination=../mocks/mock_pwned_validator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPwnedValidator is a mock of PwnedValidator interface.
type MockPwnedValidator struct {
	ctrl     *gomock.Controller
	recorder *MockPwnedValidatorMockRecorder
	isgomock struct{}
}

// MockPwnedValidatorMockRecorder is the mock recorder for MockPwnedValidator.
type MockPwnedValidatorMockRecorder struct {
	mock *MockPwnedValidator
}

// NewMockPwnedValidator creates a new mock instance.
func NewMockPwnedValidator(ctrl *gomock.Controller) *MockPwnedValidator {
	mock := &MockPwnedValidator{ctrl: ctrl}
	mock.recorder = &MockPwnedValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPwnedValidator) EXPECT() *MockPwnedValidatorMockRecorder {
	return m.recorder
}

// IsPwned mocks base method.
func (m *MockPwnedValidator) IsPwned(ctx context.Context, password string) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPwned", ctx, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsPwned indicates an expected call of IsPwned.
func (mr *MockPwnedValidatorMockRecorder) IsPwned(ctx, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPwned", reflect.TypeOf((*MockPwnedValidator)(nil).IsPwned), ctx, password)
}
