// Code generated by MockGen. DO NOT EDIT.
// Source: password_history_repository.go
//
// Generated by this command:
//
//	mockgen -source=password_history_repository.go -destination=../mocks/mock_password_history_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordHistoryRepository is a mock of PasswordHistoryRepository interface.
type MockPasswordHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordHistoryRepositoryMockRecorder is the mock recorder for MockPasswordHistoryRepository.
type MockPasswordHistoryRepositoryMockRecorder struct {
	mock *MockPasswordHistoryRepository
}

// NewMockPasswordHistoryRepository creates a new mock instance.
func NewMockPasswordHistoryRepository(ctrl *gomock.Controller) *MockPasswordHistoryRepository {
	mock := &MockPasswordHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHistoryRepository) EXPECT() *MockPasswordHistoryRepositoryMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockPasswordHistoryRepository) Cleanup(ctx context.Context, userID string, keepCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx, userID, keepCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockPasswordHistoryRepositoryMockRecorder) Cleanup(ctx, userID, keepCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockPasswordHistoryRepository)(nil).Cleanup), ctx, userID, keepCount)
}

// Create mocks base method.
func (m *MockPasswordHistoryRepository) Create(ctx context.Context, tx pgx.Tx, userID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordHistoryRepositoryMockRecorder) Create(ctx, tx, userID, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordHistoryRepository)(nil).Create), ctx, tx, userID, passwordHash)
}

// GetRecentPasswords mocks base method.
func (m *MockPasswordHistoryRepository) GetRecentPasswords(ctx context.Context, userID string, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentPasswords", ctx, userID, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentPasswords indicates an expected call of GetRecentPasswords.
func (mr *MockPasswordHistoryRepositoryMockRecorder) GetRecentPasswords(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentPasswords", reflect.TypeOf((*MockPasswordHistoryRepository)(nil).GetRecentPasswords), ctx, userID, limit)
}
