// Code generated by MockGen. DO NOT EDIT.
// Source: admin_service.go
//
// Generated by this command:
//
//	mockgen -source=admin_service.go -destination=../mocks/mock_admin_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminService is a mock of AdminService interface.
type MockAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceMockRecorder
	isgomock struct{}
}

// MockAdminServiceMockRecorder is the mock recorder for MockAdminService.
type MockAdminServiceMockRecorder struct {
	mock *MockAdminService
}

// NewMockAdminService creates a new mock instance.
func NewMockAdminService(ctrl *gomock.Controller) *MockAdminService {
	mock := &MockAdminService{ctrl: ctrl}
	mock.recorder = &MockAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService) EXPECT() *MockAdminServiceMockRecorder {
	return m.recorder
}

// ListTenants mocks base method.
func (m *MockAdminService) ListTenants(ctx context.Context) ([]*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", ctx)
	ret0, _ := ret[0].([]*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockAdminServiceMockRecorder) ListTenants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockAdminService)(nil).ListTenants), ctx)
}

// UpdateTenantStatus mocks base method.
func (m *MockAdminService) UpdateTenantStatus(ctx context.Context, tenantID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenantStatus", ctx, tenantID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenantStatus indicates an expected call of UpdateTenantStatus.
func (mr *MockAdminServiceMockRecorder) UpdateTenantStatus(ctx, tenantID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenantStatus", reflect.TypeOf((*MockAdminService)(nil).UpdateTenantStatus), ctx, tenantID, isActive)
}
