// Code generated by MockGen. DO NOT EDIT.
// Source: audit_service.go
//
// Generated by this command:
//
//	mockgen -source=audit_service.go -destination=../mocks/mock_audit_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditService is a mock of AuditService interface.
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
	isgomock struct{}
}

// MockAuditServiceMockRecorder is the mock recorder for MockAuditService.
type MockAuditServiceMockRecorder struct {
	mock *MockAuditService
}

// NewMockAuditService creates a new mock instance.
func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	mock := &MockAuditService{ctrl: ctrl}
	mock.recorder = &MockAuditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockAuditService) Log(ctx context.Context, action string, userID, tenantID *string, resourceType string, resourceID *string, oldValues, newValues any, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, action, userID, tenantID, resourceType, resourceID, oldValues, newValues, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockAuditServiceMockRecorder) Log(ctx, action, userID, tenantID, resourceType, resourceID, oldValues, newValues, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockAuditService)(nil).Log), ctx, action, userID, tenantID, resourceType, resourceID, oldValues, newValues, ip, ua)
}

// LogAction mocks base method.
func (m *MockAuditService) LogAction(ctx context.Context, action string, userID *string, resourceType string, resourceID *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAction", ctx, action, userID, resourceType, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAction indicates an expected call of LogAction.
func (mr *MockAuditServiceMockRecorder) LogAction(ctx, action, userID, resourceType, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAction", reflect.TypeOf((*MockAuditService)(nil).LogAction), ctx, action, userID, resourceType, resourceID)
}
