// Code generated by MockGen. DO NOT EDIT.
// Source: tenant_service.go
//
// Generated by this command:
//
//	mockgen -source=tenant_service.go -destination=../mocks/mock_tenant_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTenantService is a mock of TenantService interface.
type MockTenantService struct {
	ctrl     *gomock.Controller
	recorder *MockTenantServiceMockRecorder
	isgomock struct{}
}

// MockTenantServiceMockRecorder is the mock recorder for MockTenantService.
type MockTenantServiceMockRecorder struct {
	mock *MockTenantService
}

// NewMockTenantService creates a new mock instance.
func NewMockTenantService(ctrl *gomock.Controller) *MockTenantService {
	mock := &MockTenantService{ctrl: ctrl}
	mock.recorder = &MockTenantServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantService) EXPECT() *MockTenantServiceMockRecorder {
	return m.recorder
}

// AcceptInvitation mocks base method.
func (m *MockTenantService) AcceptInvitation(ctx context.Context, userID, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvitation", ctx, userID, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptInvitation indicates an expected call of AcceptInvitation.
func (mr *MockTenantServiceMockRecorder) AcceptInvitation(ctx, userID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvitation", reflect.TypeOf((*MockTenantService)(nil).AcceptInvitation), ctx, userID, tenantID)
}

// InviteMember mocks base method.
func (m *MockTenantService) InviteMember(ctx context.Context, inviterID, email, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteMember", ctx, inviterID, email, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InviteMember indicates an expected call of InviteMember.
func (mr *MockTenantServiceMockRecorder) InviteMember(ctx, inviterID, email, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteMember", reflect.TypeOf((*MockTenantService)(nil).InviteMember), ctx, inviterID, email, tenantID)
}

// UpdateSettings mocks base method.
func (m *MockTenantService) UpdateSettings(ctx context.Context, tenantID string, settings map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, tenantID, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockTenantServiceMockRecorder) UpdateSettings(ctx, tenantID, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockTenantService)(nil).UpdateSettings), ctx, tenantID, settings)
}

// UpdateStatus mocks base method.
func (m *MockTenantService) UpdateStatus(ctx context.Context, tenantID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tenantID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTenantServiceMockRecorder) UpdateStatus(ctx, tenantID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTenantService)(nil).UpdateStatus), ctx, tenantID, isActive)
}
