// Code generated by MockGen. DO NOT EDIT.
// Source: tenant_admin_service.go
//
// Generated by this command:
//
//	mockgen -source=tenant_admin_service.go -destination=../mocks/mock_tenant_admin_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantAdminService is a mock of TenantAdminService interface.
type MockTenantAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockTenantAdminServiceMockRecorder
	isgomock struct{}
}

// MockTenantAdminServiceMockRecorder is the mock recorder for MockTenantAdminService.
type MockTenantAdminServiceMockRecorder struct {
	mock *MockTenantAdminService
}

// NewMockTenantAdminService creates a new mock instance.
func NewMockTenantAdminService(ctrl *gomock.Controller) *MockTenantAdminService {
	mock := &MockTenantAdminService{ctrl: ctrl}
	mock.recorder = &MockTenantAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantAdminService) EXPECT() *MockTenantAdminServiceMockRecorder {
	return m.recorder
}

// CreateRole mocks base method.
func (m *MockTenantAdminService) CreateRole(ctx context.Context, tenantID string, role *model.Role, userID, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, tenantID, role, userID, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockTenantAdminServiceMockRecorder) CreateRole(ctx, tenantID, role, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockTenantAdminService)(nil).CreateRole), ctx, tenantID, role, userID, ip, ua)
}

// DeleteRole mocks base method.
func (m *MockTenantAdminService) DeleteRole(ctx context.Context, tenantID, roleID, userID, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, tenantID, roleID, userID, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockTenantAdminServiceMockRecorder) DeleteRole(ctx, tenantID, roleID, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockTenantAdminService)(nil).DeleteRole), ctx, tenantID, roleID, userID, ip, ua)
}

// GetTenantConfig mocks base method.
func (m *MockTenantAdminService) GetTenantConfig(ctx context.Context, tenantID string) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantConfig", ctx, tenantID)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantConfig indicates an expected call of GetTenantConfig.
func (mr *MockTenantAdminServiceMockRecorder) GetTenantConfig(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantConfig", reflect.TypeOf((*MockTenantAdminService)(nil).GetTenantConfig), ctx, tenantID)
}

// ListMembers mocks base method.
func (m *MockTenantAdminService) ListMembers(ctx context.Context, tenantID string) ([]model.TenantMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, tenantID)
	ret0, _ := ret[0].([]model.TenantMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockTenantAdminServiceMockRecorder) ListMembers(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockTenantAdminService)(nil).ListMembers), ctx, tenantID)
}

// ListRoles mocks base method.
func (m *MockTenantAdminService) ListRoles(ctx context.Context, tenantID string) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx, tenantID)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockTenantAdminServiceMockRecorder) ListRoles(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockTenantAdminService)(nil).ListRoles), ctx, tenantID)
}

// RemoveMember mocks base method.
func (m *MockTenantAdminService) RemoveMember(ctx context.Context, tenantID, membershipID, userID, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, tenantID, membershipID, userID, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTenantAdminServiceMockRecorder) RemoveMember(ctx, tenantID, membershipID, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTenantAdminService)(nil).RemoveMember), ctx, tenantID, membershipID, userID, ip, ua)
}

// UpdateMemberRoles mocks base method.
func (m *MockTenantAdminService) UpdateMemberRoles(ctx context.Context, tenantID, membershipID string, roleIDs []string, userID, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRoles", ctx, tenantID, membershipID, roleIDs, userID, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRoles indicates an expected call of UpdateMemberRoles.
func (mr *MockTenantAdminServiceMockRecorder) UpdateMemberRoles(ctx, tenantID, membershipID, roleIDs, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRoles", reflect.TypeOf((*MockTenantAdminService)(nil).UpdateMemberRoles), ctx, tenantID, membershipID, roleIDs, userID, ip, ua)
}

// UpdateMemberStatus mocks base method.
func (m *MockTenantAdminService) UpdateMemberStatus(ctx context.Context, tenantID, membershipID, status, userID, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberStatus", ctx, tenantID, membershipID, status, userID, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberStatus indicates an expected call of UpdateMemberStatus.
func (mr *MockTenantAdminServiceMockRecorder) UpdateMemberStatus(ctx, tenantID, membershipID, status, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberStatus", reflect.TypeOf((*MockTenantAdminService)(nil).UpdateMemberStatus), ctx, tenantID, membershipID, status, userID, ip, ua)
}

// UpdateRole mocks base method.
func (m *MockTenantAdminService) UpdateRole(ctx context.Context, tenantID string, role *model.Role, userID, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, tenantID, role, userID, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockTenantAdminServiceMockRecorder) UpdateRole(ctx, tenantID, role, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockTenantAdminService)(nil).UpdateRole), ctx, tenantID, role, userID, ip, ua)
}

// UpdateTenantConfig mocks base method.
func (m *MockTenantAdminService) UpdateTenantConfig(ctx context.Context, tenantID string, settings map[string]any, userID, ip, ua string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenantConfig", ctx, tenantID, settings, userID, ip, ua)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenantConfig indicates an expected call of UpdateTenantConfig.
func (mr *MockTenantAdminServiceMockRecorder) UpdateTenantConfig(ctx, tenantID, settings, userID, ip, ua any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenantConfig", reflect.TypeOf((*MockTenantAdminService)(nil).UpdateTenantConfig), ctx, tenantID, settings, userID, ip, ua)
}
