// Code generated by MockGen. DO NOT EDIT.
// Source: permission_cache.go
//
// Generated by this command:
//
//	mockgen -source=permission_cache.go -destination=../../mocks/mock_permission_cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionCache is a mock of PermissionCache interface.
type MockPermissionCache struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionCacheMockRecorder
	isgomock struct{}
}

// MockPermissionCacheMockRecorder is the mock recorder for MockPermissionCache.
type MockPermissionCacheMockRecorder struct {
	mock *MockPermissionCache
}

// NewMockPermissionCache creates a new mock instance.
func NewMockPermissionCache(ctrl *gomock.Controller) *MockPermissionCache {
	mock := &MockPermissionCache{ctrl: ctrl}
	mock.recorder = &MockPermissionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionCache) EXPECT() *MockPermissionCacheMockRecorder {
	return m.recorder
}

// GetPermissions mocks base method.
func (m *MockPermissionCache) GetPermissions(ctx context.Context, tenantID, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", ctx, tenantID, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockPermissionCacheMockRecorder) GetPermissions(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockPermissionCache)(nil).GetPermissions), ctx, tenantID, userID)
}

// GetRoles mocks base method.
func (m *MockPermissionCache) GetRoles(ctx context.Context, tenantID, userID string) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", ctx, tenantID, userID)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockPermissionCacheMockRecorder) GetRoles(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockPermissionCache)(nil).GetRoles), ctx, tenantID, userID)
}

// Invalidate mocks base method.
func (m *MockPermissionCache) Invalidate(ctx context.Context, tenantID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, tenantID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockPermissionCacheMockRecorder) Invalidate(ctx, tenantID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockPermissionCache)(nil).Invalidate), ctx, tenantID, userID)
}

// SetPermissions mocks base method.
func (m *MockPermissionCache) SetPermissions(ctx context.Context, tenantID, userID string, permissions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPermissions", ctx, tenantID, userID, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPermissions indicates an expected call of SetPermissions.
func (mr *MockPermissionCacheMockRecorder) SetPermissions(ctx, tenantID, userID, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermissions", reflect.TypeOf((*MockPermissionCache)(nil).SetPermissions), ctx, tenantID, userID, permissions)
}

// SetRoles mocks base method.
func (m *MockPermissionCache) SetRoles(ctx context.Context, tenantID, userID string, roles []model.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoles", ctx, tenantID, userID, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoles indicates an expected call of SetRoles.
func (mr *MockPermissionCacheMockRecorder) SetRoles(ctx, tenantID, userID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoles", reflect.TypeOf((*MockPermissionCache)(nil).SetRoles), ctx, tenantID, userID, roles)
}
