// Code generated by MockGen. DO NOT EDIT.
// Source: trusted_device_repository.go
//
// Generated by this command:
//
//	mockgen -source=trusted_device_repository.go -destination=../mocks/mock_trusted_device_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTrustedDeviceRepository is a mock of TrustedDeviceRepository interface.
type MockTrustedDeviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTrustedDeviceRepositoryMockRecorder
	isgomock struct{}
}

// MockTrustedDeviceRepositoryMockRecorder is the mock recorder for MockTrustedDeviceRepository.
type MockTrustedDeviceRepositoryMockRecorder struct {
	mock *MockTrustedDeviceRepository
}

// NewMockTrustedDeviceRepository creates a new mock instance.
func NewMockTrustedDeviceRepository(ctrl *gomock.Controller) *MockTrustedDeviceRepository {
	mock := &MockTrustedDeviceRepository{ctrl: ctrl}
	mock.recorder = &MockTrustedDeviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrustedDeviceRepository) EXPECT() *MockTrustedDeviceRepositoryMockRecorder {
	return m.recorder
}

// DeleteExpired mocks base method.
func (m *MockTrustedDeviceRepository) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockTrustedDeviceRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockTrustedDeviceRepository)(nil).DeleteExpired), ctx)
}

// FindByUserAndFingerprint mocks base method.
func (m *MockTrustedDeviceRepository) FindByUserAndFingerprint(ctx context.Context, userID, fingerprint string) (*model.TrustedDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserAndFingerprint", ctx, userID, fingerprint)
	ret0, _ := ret[0].(*model.TrustedDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserAndFingerprint indicates an expected call of FindByUserAndFingerprint.
func (mr *MockTrustedDeviceRepositoryMockRecorder) FindByUserAndFingerprint(ctx, userID, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserAndFingerprint", reflect.TypeOf((*MockTrustedDeviceRepository)(nil).FindByUserAndFingerprint), ctx, userID, fingerprint)
}

// Upsert mocks base method.
func (m *MockTrustedDeviceRepository) Upsert(ctx context.Context, tx pgx.Tx, device *model.TrustedDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, tx, device)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTrustedDeviceRepositoryMockRecorder) Upsert(ctx, tx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTrustedDeviceRepository)(nil).Upsert), ctx, tx, device)
}
