// Code generated by MockGen. DO NOT EDIT.
// Source: tenant_repository.go
//
// Generated by this command:
//
//	mockgen -source=tenant_repository.go -destination=../mocks/mock_tenant_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// FindBySlug mocks base method.
func (m *MockTenantRepository) FindBySlug(ctx context.Context, slug string) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockTenantRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockTenantRepository)(nil).FindBySlug), ctx, slug)
}

// MockTenantMembershipRepository is a mock of TenantMembershipRepository interface.
type MockTenantMembershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantMembershipRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantMembershipRepositoryMockRecorder is the mock recorder for MockTenantMembershipRepository.
type MockTenantMembershipRepositoryMockRecorder struct {
	mock *MockTenantMembershipRepository
}

// NewMockTenantMembershipRepository creates a new mock instance.
func NewMockTenantMembershipRepository(ctrl *gomock.Controller) *MockTenantMembershipRepository {
	mock := &MockTenantMembershipRepository{ctrl: ctrl}
	mock.recorder = &MockTenantMembershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantMembershipRepository) EXPECT() *MockTenantMembershipRepositoryMockRecorder {
	return m.recorder
}

// ActivateByUserID mocks base method.
func (m *MockTenantMembershipRepository) ActivateByUserID(ctx context.Context, tx pgx.Tx, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateByUserID", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateByUserID indicates an expected call of ActivateByUserID.
func (mr *MockTenantMembershipRepositoryMockRecorder) ActivateByUserID(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateByUserID", reflect.TypeOf((*MockTenantMembershipRepository)(nil).ActivateByUserID), ctx, tx, userID)
}

// Create mocks base method.
func (m *MockTenantMembershipRepository) Create(ctx context.Context, tx pgx.Tx, membership *model.TenantMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantMembershipRepositoryMockRecorder) Create(ctx, tx, membership any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantMembershipRepository)(nil).Create), ctx, tx, membership)
}

// FindActiveByUserID mocks base method.
func (m *MockTenantMembershipRepository) FindActiveByUserID(ctx context.Context, userID string) (*model.TenantMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.TenantMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByUserID indicates an expected call of FindActiveByUserID.
func (mr *MockTenantMembershipRepositoryMockRecorder) FindActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByUserID", reflect.TypeOf((*MockTenantMembershipRepository)(nil).FindActiveByUserID), ctx, userID)
}

// FindPermissionsByUserAndTenant mocks base method.
func (m *MockTenantMembershipRepository) FindPermissionsByUserAndTenant(ctx context.Context, userID, tenantID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPermissionsByUserAndTenant", ctx, userID, tenantID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPermissionsByUserAndTenant indicates an expected call of FindPermissionsByUserAndTenant.
func (mr *MockTenantMembershipRepositoryMockRecorder) FindPermissionsByUserAndTenant(ctx, userID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPermissionsByUserAndTenant", reflect.TypeOf((*MockTenantMembershipRepository)(nil).FindPermissionsByUserAndTenant), ctx, userID, tenantID)
}

// FindRolesByMembership mocks base method.
func (m *MockTenantMembershipRepository) FindRolesByMembership(ctx context.Context, membershipID string) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByMembership", ctx, membershipID)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByMembership indicates an expected call of FindRolesByMembership.
func (mr *MockTenantMembershipRepositoryMockRecorder) FindRolesByMembership(ctx, membershipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByMembership", reflect.TypeOf((*MockTenantMembershipRepository)(nil).FindRolesByMembership), ctx, membershipID)
}
