// Code generated by MockGen. DO NOT EDIT.
// Source: session_cache.go
//
// Generated by this command:
//
//	mockgen -source=session_cache.go -destination=../../mocks/mock_session_cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	redis "github.com/herdifirdausss/auth/internal/infrastructure/redis"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionCache is a mock of SessionCache interface.
type MockSessionCache struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCacheMockRecorder
	isgomock struct{}
}

// MockSessionCacheMockRecorder is the mock recorder for MockSessionCache.
type MockSessionCacheMockRecorder struct {
	mock *MockSessionCache
}

// NewMockSessionCache creates a new mock instance.
func NewMockSessionCache(ctrl *gomock.Controller) *MockSessionCache {
	mock := &MockSessionCache{ctrl: ctrl}
	mock.recorder = &MockSessionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCache) EXPECT() *MockSessionCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionCache) Delete(ctx context.Context, userID, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionCacheMockRecorder) Delete(ctx, userID, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionCache)(nil).Delete), ctx, userID, tokenHash)
}

// DeleteByUserID mocks base method.
func (m *MockSessionCache) DeleteByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockSessionCacheMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockSessionCache)(nil).DeleteByUserID), ctx, userID)
}

// Get mocks base method.
func (m *MockSessionCache) Get(ctx context.Context, tokenHash string) (*redis.CachedSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tokenHash)
	ret0, _ := ret[0].(*redis.CachedSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionCacheMockRecorder) Get(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionCache)(nil).Get), ctx, tokenHash)
}

// Set mocks base method.
func (m *MockSessionCache) Set(ctx context.Context, tokenHash string, session *redis.CachedSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, tokenHash, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSessionCacheMockRecorder) Set(ctx, tokenHash, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSessionCache)(nil).Set), ctx, tokenHash, session)
}
