// Code generated by MockGen. DO NOT EDIT.
// Source: mfa_service.go
//
// Generated by this command:
//
//	mockgen -source=mfa_service.go -destination=../mocks/mock_mfa_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMFAService is a mock of MFAService interface.
type MockMFAService struct {
	ctrl     *gomock.Controller
	recorder *MockMFAServiceMockRecorder
	isgomock struct{}
}

// MockMFAServiceMockRecorder is the mock recorder for MockMFAService.
type MockMFAServiceMockRecorder struct {
	mock *MockMFAService
}

// NewMockMFAService creates a new mock instance.
func NewMockMFAService(ctrl *gomock.Controller) *MockMFAService {
	mock := &MockMFAService{ctrl: ctrl}
	mock.recorder = &MockMFAServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFAService) EXPECT() *MockMFAServiceMockRecorder {
	return m.recorder
}

// Challenge mocks base method.
func (m *MockMFAService) Challenge(ctx context.Context, req model.ChallengeRequest, ip, ua, fingerprint string) (*model.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Challenge", ctx, req, ip, ua, fingerprint)
	ret0, _ := ret[0].(*model.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Challenge indicates an expected call of Challenge.
func (mr *MockMFAServiceMockRecorder) Challenge(ctx, req, ip, ua, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Challenge", reflect.TypeOf((*MockMFAService)(nil).Challenge), ctx, req, ip, ua, fingerprint)
}

// DisableMFA mocks base method.
func (m *MockMFAService) DisableMFA(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableMFA", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableMFA indicates an expected call of DisableMFA.
func (mr *MockMFAServiceMockRecorder) DisableMFA(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableMFA", reflect.TypeOf((*MockMFAService)(nil).DisableMFA), ctx, userID)
}

// SetupTOTP mocks base method.
func (m *MockMFAService) SetupTOTP(ctx context.Context, userID, email string) (*model.SetupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupTOTP", ctx, userID, email)
	ret0, _ := ret[0].(*model.SetupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupTOTP indicates an expected call of SetupTOTP.
func (mr *MockMFAServiceMockRecorder) SetupTOTP(ctx, userID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupTOTP", reflect.TypeOf((*MockMFAService)(nil).SetupTOTP), ctx, userID, email)
}

// VerifySetup mocks base method.
func (m *MockMFAService) VerifySetup(ctx context.Context, userID, otpCode string) (*model.VerifySetupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySetup", ctx, userID, otpCode)
	ret0, _ := ret[0].(*model.VerifySetupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifySetup indicates an expected call of VerifySetup.
func (mr *MockMFAServiceMockRecorder) VerifySetup(ctx, userID, otpCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySetup", reflect.TypeOf((*MockMFAService)(nil).VerifySetup), ctx, userID, otpCode)
}
