// Code generated by MockGen. DO NOT EDIT.
// Source: risk_service.go
//
// Generated by this command:
//
//	mockgen -source=risk_service.go -destination=../mocks/mock_risk_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRiskService is a mock of RiskService interface.
type MockRiskService struct {
	ctrl     *gomock.Controller
	recorder *MockRiskServiceMockRecorder
	isgomock struct{}
}

// MockRiskServiceMockRecorder is the mock recorder for MockRiskService.
type MockRiskServiceMockRecorder struct {
	mock *MockRiskService
}

// NewMockRiskService creates a new mock instance.
func NewMockRiskService(ctrl *gomock.Controller) *MockRiskService {
	mock := &MockRiskService{ctrl: ctrl}
	mock.recorder = &MockRiskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRiskService) EXPECT() *MockRiskServiceMockRecorder {
	return m.recorder
}

// AnalyzeLoginRisk mocks base method.
func (m *MockRiskService) AnalyzeLoginRisk(ctx context.Context, userID, ip, fingerprint string) (*model.RiskAssessment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeLoginRisk", ctx, userID, ip, fingerprint)
	ret0, _ := ret[0].(*model.RiskAssessment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeLoginRisk indicates an expected call of AnalyzeLoginRisk.
func (mr *MockRiskServiceMockRecorder) AnalyzeLoginRisk(ctx, userID, ip, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeLoginRisk", reflect.TypeOf((*MockRiskService)(nil).AnalyzeLoginRisk), ctx, userID, ip, fingerprint)
}
