// Code generated by MockGen. DO NOT EDIT.
// Source: webauthn_service.go
//
// Generated by this command:
//
//	mockgen -source=webauthn_service.go -destination=../mocks/mock_webauthn_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	protocol "github.com/go-webauthn/webauthn/protocol"
	model "github.com/herdifirdausss/auth/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockWebAuthnService is a mock of WebAuthnService interface.
type MockWebAuthnService struct {
	ctrl     *gomock.Controller
	recorder *MockWebAuthnServiceMockRecorder
	isgomock struct{}
}

// MockWebAuthnServiceMockRecorder is the mock recorder for MockWebAuthnService.
type MockWebAuthnServiceMockRecorder struct {
	mock *MockWebAuthnService
}

// NewMockWebAuthnService creates a new mock instance.
func NewMockWebAuthnService(ctrl *gomock.Controller) *MockWebAuthnService {
	mock := &MockWebAuthnService{ctrl: ctrl}
	mock.recorder = &MockWebAuthnServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAuthnService) EXPECT() *MockWebAuthnServiceMockRecorder {
	return m.recorder
}

// BeginLogin mocks base method.
func (m *MockWebAuthnService) BeginLogin(ctx context.Context, email string) (*protocol.CredentialAssertion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginLogin", ctx, email)
	ret0, _ := ret[0].(*protocol.CredentialAssertion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginLogin indicates an expected call of BeginLogin.
func (mr *MockWebAuthnServiceMockRecorder) BeginLogin(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginLogin", reflect.TypeOf((*MockWebAuthnService)(nil).BeginLogin), ctx, email)
}

// BeginRegistration mocks base method.
func (m *MockWebAuthnService) BeginRegistration(ctx context.Context, userID string) (*protocol.CredentialCreation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginRegistration", ctx, userID)
	ret0, _ := ret[0].(*protocol.CredentialCreation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginRegistration indicates an expected call of BeginRegistration.
func (mr *MockWebAuthnServiceMockRecorder) BeginRegistration(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRegistration", reflect.TypeOf((*MockWebAuthnService)(nil).BeginRegistration), ctx, userID)
}

// FinishLogin mocks base method.
func (m *MockWebAuthnService) FinishLogin(ctx context.Context, loginSessionID string, responseBody []byte) (*model.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishLogin", ctx, loginSessionID, responseBody)
	ret0, _ := ret[0].(*model.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishLogin indicates an expected call of FinishLogin.
func (mr *MockWebAuthnServiceMockRecorder) FinishLogin(ctx, loginSessionID, responseBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishLogin", reflect.TypeOf((*MockWebAuthnService)(nil).FinishLogin), ctx, loginSessionID, responseBody)
}

// FinishRegistration mocks base method.
func (m *MockWebAuthnService) FinishRegistration(ctx context.Context, userID string, responseBody []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishRegistration", ctx, userID, responseBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishRegistration indicates an expected call of FinishRegistration.
func (mr *MockWebAuthnServiceMockRecorder) FinishRegistration(ctx, userID, responseBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishRegistration", reflect.TypeOf((*MockWebAuthnService)(nil).FinishRegistration), ctx, userID, responseBody)
}
