// Code generated by MockGen. DO NOT EDIT.
// Source: session_repository.go
//
// Generated by this command:
//
//	mockgen -source=session_repository.go -destination=../mocks/mock_session_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CleanupExpired mocks base method.
func (m *MockSessionRepository) CleanupExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpired indicates an expected call of CleanupExpired.
func (mr *MockSessionRepositoryMockRecorder) CleanupExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpired", reflect.TypeOf((*MockSessionRepository)(nil).CleanupExpired), ctx)
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, tx pgx.Tx, session *model.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, tx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, tx, session)
}

// FindByID mocks base method.
func (m *MockSessionRepository) FindByID(ctx context.Context, id string) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSessionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSessionRepository)(nil).FindByID), ctx, id)
}

// FindByTokenHash mocks base method.
func (m *MockSessionRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockSessionRepositoryMockRecorder) FindByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).FindByTokenHash), ctx, tokenHash)
}

// RevokeAllByUser mocks base method.
func (m *MockSessionRepository) RevokeAllByUser(ctx context.Context, tx pgx.Tx, userID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByUser", ctx, tx, userID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllByUser indicates an expected call of RevokeAllByUser.
func (mr *MockSessionRepositoryMockRecorder) RevokeAllByUser(ctx, tx, userID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByUser", reflect.TypeOf((*MockSessionRepository)(nil).RevokeAllByUser), ctx, tx, userID, reason)
}

// RevokeByID mocks base method.
func (m *MockSessionRepository) RevokeByID(ctx context.Context, sessionID, reason, revokedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByID", ctx, sessionID, reason, revokedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByID indicates an expected call of RevokeByID.
func (mr *MockSessionRepositoryMockRecorder) RevokeByID(ctx, sessionID, reason, revokedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByID", reflect.TypeOf((*MockSessionRepository)(nil).RevokeByID), ctx, sessionID, reason, revokedBy)
}

// UpdateActivity mocks base method.
func (m *MockSessionRepository) UpdateActivity(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *MockSessionRepositoryMockRecorder) UpdateActivity(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*MockSessionRepository)(nil).UpdateActivity), ctx, sessionID)
}

// UpdateTokenHash mocks base method.
func (m *MockSessionRepository) UpdateTokenHash(ctx context.Context, tx pgx.Tx, sessionID, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokenHash", ctx, tx, sessionID, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokenHash indicates an expected call of UpdateTokenHash.
func (mr *MockSessionRepositoryMockRecorder) UpdateTokenHash(ctx, tx, sessionID, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).UpdateTokenHash), ctx, tx, sessionID, tokenHash)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// CleanupExpired mocks base method.
func (m *MockRefreshTokenRepository) CleanupExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpired indicates an expected call of CleanupExpired.
func (mr *MockRefreshTokenRepositoryMockRecorder) CleanupExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpired", reflect.TypeOf((*MockRefreshTokenRepository)(nil).CleanupExpired), ctx)
}

// Create mocks base method.
func (m *MockRefreshTokenRepository) Create(ctx context.Context, tx pgx.Tx, token *model.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepositoryMockRecorder) Create(ctx, tx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Create), ctx, tx, token)
}

// FindByTokenHash mocks base method.
func (m *MockRefreshTokenRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*model.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*model.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockRefreshTokenRepositoryMockRecorder) FindByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockRefreshTokenRepository)(nil).FindByTokenHash), ctx, tokenHash)
}

// MarkUsed mocks base method.
func (m *MockRefreshTokenRepository) MarkUsed(ctx context.Context, tx pgx.Tx, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, tx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockRefreshTokenRepositoryMockRecorder) MarkUsed(ctx, tx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockRefreshTokenRepository)(nil).MarkUsed), ctx, tx, tokenID)
}

// RevokeAllByUser mocks base method.
func (m *MockRefreshTokenRepository) RevokeAllByUser(ctx context.Context, tx pgx.Tx, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByUser", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllByUser indicates an expected call of RevokeAllByUser.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeAllByUser(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByUser", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeAllByUser), ctx, tx, userID)
}

// RevokeByFamily mocks base method.
func (m *MockRefreshTokenRepository) RevokeByFamily(ctx context.Context, tx pgx.Tx, familyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByFamily", ctx, tx, familyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByFamily indicates an expected call of RevokeByFamily.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeByFamily(ctx, tx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByFamily", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeByFamily), ctx, tx, familyID)
}

// RevokeBySessionID mocks base method.
func (m *MockRefreshTokenRepository) RevokeBySessionID(ctx context.Context, tx pgx.Tx, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeBySessionID", ctx, tx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeBySessionID indicates an expected call of RevokeBySessionID.
func (mr *MockRefreshTokenRepositoryMockRecorder) RevokeBySessionID(ctx, tx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeBySessionID", reflect.TypeOf((*MockRefreshTokenRepository)(nil).RevokeBySessionID), ctx, tx, sessionID)
}
