// Code generated by MockGen. DO NOT EDIT.
// Source: mfa_repository.go
//
// Generated by this command:
//
//	mockgen -source=mfa_repository.go -destination=../mocks/mock_mfa_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockMFARepository is a mock of MFARepository interface.
type MockMFARepository struct {
	ctrl     *gomock.Controller
	recorder *MockMFARepositoryMockRecorder
	isgomock struct{}
}

// MockMFARepositoryMockRecorder is the mock recorder for MockMFARepository.
type MockMFARepositoryMockRecorder struct {
	mock *MockMFARepository
}

// NewMockMFARepository creates a new mock instance.
func NewMockMFARepository(ctrl *gomock.Controller) *MockMFARepository {
	mock := &MockMFARepository{ctrl: ctrl}
	mock.recorder = &MockMFARepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFARepository) EXPECT() *MockMFARepositoryMockRecorder {
	return m.recorder
}

// Activate mocks base method.
func (m *MockMFARepository) Activate(ctx context.Context, tx pgx.Tx, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockMFARepositoryMockRecorder) Activate(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockMFARepository)(nil).Activate), ctx, tx, id)
}

// Create mocks base method.
func (m *MockMFARepository) Create(ctx context.Context, method *model.MFAMethod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, method)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMFARepositoryMockRecorder) Create(ctx, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMFARepository)(nil).Create), ctx, method)
}

// DeactivateAll mocks base method.
func (m *MockMFARepository) DeactivateAll(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateAll", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateAll indicates an expected call of DeactivateAll.
func (mr *MockMFARepositoryMockRecorder) DeactivateAll(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateAll", reflect.TypeOf((*MockMFARepository)(nil).DeactivateAll), ctx, userID)
}

// FindAllByUserIDAndType mocks base method.
func (m *MockMFARepository) FindAllByUserIDAndType(ctx context.Context, userID, methodType string) ([]*model.MFAMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserIDAndType", ctx, userID, methodType)
	ret0, _ := ret[0].([]*model.MFAMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserIDAndType indicates an expected call of FindAllByUserIDAndType.
func (mr *MockMFARepositoryMockRecorder) FindAllByUserIDAndType(ctx, userID, methodType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserIDAndType", reflect.TypeOf((*MockMFARepository)(nil).FindAllByUserIDAndType), ctx, userID, methodType)
}

// FindInactiveByUser mocks base method.
func (m *MockMFARepository) FindInactiveByUser(ctx context.Context, userID, methodType string) (*model.MFAMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInactiveByUser", ctx, userID, methodType)
	ret0, _ := ret[0].(*model.MFAMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInactiveByUser indicates an expected call of FindInactiveByUser.
func (mr *MockMFARepositoryMockRecorder) FindInactiveByUser(ctx, userID, methodType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInactiveByUser", reflect.TypeOf((*MockMFARepository)(nil).FindInactiveByUser), ctx, userID, methodType)
}

// FindPrimaryActive mocks base method.
func (m *MockMFARepository) FindPrimaryActive(ctx context.Context, userID string) (*model.MFAMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrimaryActive", ctx, userID)
	ret0, _ := ret[0].(*model.MFAMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrimaryActive indicates an expected call of FindPrimaryActive.
func (mr *MockMFARepositoryMockRecorder) FindPrimaryActive(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrimaryActive", reflect.TypeOf((*MockMFARepository)(nil).FindPrimaryActive), ctx, userID)
}

// IncrementUseCount mocks base method.
func (m *MockMFARepository) IncrementUseCount(ctx context.Context, tx pgx.Tx, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUseCount", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUseCount indicates an expected call of IncrementUseCount.
func (mr *MockMFARepositoryMockRecorder) IncrementUseCount(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUseCount", reflect.TypeOf((*MockMFARepository)(nil).IncrementUseCount), ctx, tx, id)
}

// SetBackupCodes mocks base method.
func (m *MockMFARepository) SetBackupCodes(ctx context.Context, tx pgx.Tx, id, encrypted string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBackupCodes", ctx, tx, id, encrypted)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBackupCodes indicates an expected call of SetBackupCodes.
func (mr *MockMFARepositoryMockRecorder) SetBackupCodes(ctx, tx, id, encrypted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBackupCodes", reflect.TypeOf((*MockMFARepository)(nil).SetBackupCodes), ctx, tx, id, encrypted)
}
