// Code generated by MockGen. DO NOT EDIT.
// Source: membership_role_repository.go
//
// Generated by this command:
//
//	mockgen -source=membership_role_repository.go -destination=../mocks/mock_membership_role_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockMembershipRoleRepository is a mock of MembershipRoleRepository interface.
type MockMembershipRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockMembershipRoleRepositoryMockRecorder is the mock recorder for MockMembershipRoleRepository.
type MockMembershipRoleRepositoryMockRecorder struct {
	mock *MockMembershipRoleRepository
}

// NewMockMembershipRoleRepository creates a new mock instance.
func NewMockMembershipRoleRepository(ctrl *gomock.Controller) *MockMembershipRoleRepository {
	mock := &MockMembershipRoleRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRoleRepository) EXPECT() *MockMembershipRoleRepositoryMockRecorder {
	return m.recorder
}

// AddRole mocks base method.
func (m *MockMembershipRoleRepository) AddRole(ctx context.Context, tx pgx.Tx, membershipID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRole", ctx, tx, membershipID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRole indicates an expected call of AddRole.
func (mr *MockMembershipRoleRepositoryMockRecorder) AddRole(ctx, tx, membershipID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRole", reflect.TypeOf((*MockMembershipRoleRepository)(nil).AddRole), ctx, tx, membershipID, roleID)
}

// RemoveAllRoles mocks base method.
func (m *MockMembershipRoleRepository) RemoveAllRoles(ctx context.Context, tx pgx.Tx, membershipID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllRoles", ctx, tx, membershipID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllRoles indicates an expected call of RemoveAllRoles.
func (mr *MockMembershipRoleRepositoryMockRecorder) RemoveAllRoles(ctx, tx, membershipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllRoles", reflect.TypeOf((*MockMembershipRoleRepository)(nil).RemoveAllRoles), ctx, tx, membershipID)
}

// RemoveRole mocks base method.
func (m *MockMembershipRoleRepository) RemoveRole(ctx context.Context, tx pgx.Tx, membershipID, roleID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, tx, membershipID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockMembershipRoleRepositoryMockRecorder) RemoveRole(ctx, tx, membershipID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockMembershipRoleRepository)(nil).RemoveRole), ctx, tx, membershipID, roleID)
}
