// Code generated by MockGen. DO NOT EDIT.
// Source: role_repository.go
//
// Generated by this command:
//
//	mockgen -source=role_repository.go -destination=mock_role_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// FindPermissionsByUserAndTenant mocks base method.
func (m *MockRoleRepository) FindPermissionsByUserAndTenant(ctx context.Context, userID, tenantID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPermissionsByUserAndTenant", ctx, userID, tenantID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPermissionsByUserAndTenant indicates an expected call of FindPermissionsByUserAndTenant.
func (mr *MockRoleRepositoryMockRecorder) FindPermissionsByUserAndTenant(ctx, userID, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPermissionsByUserAndTenant", reflect.TypeOf((*MockRoleRepository)(nil).FindPermissionsByUserAndTenant), ctx, userID, tenantID)
}

// FindRolesByMembership mocks base method.
func (m *MockRoleRepository) FindRolesByMembership(ctx context.Context, membershipID string) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRolesByMembership", ctx, membershipID)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRolesByMembership indicates an expected call of FindRolesByMembership.
func (mr *MockRoleRepositoryMockRecorder) FindRolesByMembership(ctx, membershipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRolesByMembership", reflect.TypeOf((*MockRoleRepository)(nil).FindRolesByMembership), ctx, membershipID)
}
