// Code generated by MockGen. DO NOT EDIT.
// Source: credential_repository.go
//
// Generated by this command:
//
//	mockgen -source=credential_repository.go -destination=mock_credential_repository.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/herdifirdausss/auth/internal/model"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCredentialRepository) Create(ctx context.Context, tx pgx.Tx, cred *model.UserCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCredentialRepositoryMockRecorder) Create(ctx, tx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCredentialRepository)(nil).Create), ctx, tx, cred)
}

// FindByUserID mocks base method.
func (m *MockCredentialRepository) FindByUserID(ctx context.Context, userID string) (*model.UserCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*model.UserCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockCredentialRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockCredentialRepository)(nil).FindByUserID), ctx, userID)
}

// UpdatePassword mocks base method.
func (m *MockCredentialRepository) UpdatePassword(ctx context.Context, tx pgx.Tx, userID, hash, salt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, tx, userID, hash, salt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockCredentialRepositoryMockRecorder) UpdatePassword(ctx, tx, userID, hash, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockCredentialRepository)(nil).UpdatePassword), ctx, tx, userID, hash, salt)
}

// MockSecurityTokenRepository is a mock of SecurityTokenRepository interface.
type MockSecurityTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockSecurityTokenRepositoryMockRecorder is the mock recorder for MockSecurityTokenRepository.
type MockSecurityTokenRepositoryMockRecorder struct {
	mock *MockSecurityTokenRepository
}

// NewMockSecurityTokenRepository creates a new mock instance.
func NewMockSecurityTokenRepository(ctrl *gomock.Controller) *MockSecurityTokenRepository {
	mock := &MockSecurityTokenRepository{ctrl: ctrl}
	mock.recorder = &MockSecurityTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityTokenRepository) EXPECT() *MockSecurityTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecurityTokenRepository) Create(ctx context.Context, token *model.SecurityToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecurityTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecurityTokenRepository)(nil).Create), ctx, token)
}

// FindValidToken mocks base method.
func (m *MockSecurityTokenRepository) FindValidToken(ctx context.Context, tokenHash, tokenType string) (*model.SecurityToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindValidToken", ctx, tokenHash, tokenType)
	ret0, _ := ret[0].(*model.SecurityToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindValidToken indicates an expected call of FindValidToken.
func (mr *MockSecurityTokenRepositoryMockRecorder) FindValidToken(ctx, tokenHash, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindValidToken", reflect.TypeOf((*MockSecurityTokenRepository)(nil).FindValidToken), ctx, tokenHash, tokenType)
}

// MarkUsed mocks base method.
func (m *MockSecurityTokenRepository) MarkUsed(ctx context.Context, tx pgx.Tx, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, tx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockSecurityTokenRepositoryMockRecorder) MarkUsed(ctx, tx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockSecurityTokenRepository)(nil).MarkUsed), ctx, tx, tokenID)
}

// MockSecurityEventRepository is a mock of SecurityEventRepository interface.
type MockSecurityEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityEventRepositoryMockRecorder
	isgomock struct{}
}

// MockSecurityEventRepositoryMockRecorder is the mock recorder for MockSecurityEventRepository.
type MockSecurityEventRepositoryMockRecorder struct {
	mock *MockSecurityEventRepository
}

// NewMockSecurityEventRepository creates a new mock instance.
func NewMockSecurityEventRepository(ctrl *gomock.Controller) *MockSecurityEventRepository {
	mock := &MockSecurityEventRepository{ctrl: ctrl}
	mock.recorder = &MockSecurityEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityEventRepository) EXPECT() *MockSecurityEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecurityEventRepository) Create(ctx context.Context, event *model.SecurityEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecurityEventRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecurityEventRepository)(nil).Create), ctx, event)
}
